# features module

include($$PWD/keyboard/third_party/pinyin/pinyin.pri)

SOURCES += \
    $$PWD/auth/ui/AccountSelectDialog.cpp \
    $$PWD/auth/ui/loginpage.cpp \
    $$PWD/auth/application/LoginController.cpp \
    $$PWD/auth/application/AuthFlowCoordinator.cpp \
    $$PWD/auth/infra/password/authservice.cpp \
    $$PWD/auth/infra/password/AuthServiceAdapter.cpp \
    $$PWD/auth/infra/http/AuthGatewayAdapter.cpp \
    $$PWD/auth/infra/device/MockCredentialSource.cpp \
    $$PWD/auth/infra/device/CardSerialSource.cpp \
    $$PWD/auth/infra/device/FingerprintSource.cpp \
    $$PWD/workbench/ui/workbenchpage.cpp \
    $$PWD/workbench/application/WorkbenchController.cpp \
    $$PWD/keyboard/application/KeyboardController.cpp \
    $$PWD/keyboard/application/KeyboardModeResolver.cpp \
    $$PWD/keyboard/application/KeyboardPagePolicy.cpp \
    $$PWD/keyboard/application/KeyboardPinyinEngine.cpp \
    $$PWD/keyboard/application/KeyboardSizingPolicy.cpp \
    $$PWD/keyboard/application/KeyboardTargetAdapter.cpp \
    $$PWD/keyboard/application/pinyindecoderservice.cpp \
    $$PWD/keyboard/ui/KeyboardContainer.cpp \
    $$PWD/keyboard/ui/CandidateBarWidget.cpp \
    $$PWD/keyboard/ui/NormalKeyboard.cpp \
    $$PWD/keyboard/ui/NumKeyboard.cpp \
    $$PWD/keyboard/ui/SymbolKeyboard.cpp \
    $$PWD/keyboard/ui/UrlKeyboard.cpp \
    $$PWD/key/ui/keymanagepage.cpp \
    $$PWD/key/application/KeySessionService.cpp \
    $$PWD/key/application/KeyManageController.cpp \
    $$PWD/key/application/SerialLogManager.cpp \
    $$PWD/key/application/KeyProvisioningService.cpp \
    $$PWD/key/application/TicketReturnHttpClient.cpp \
    $$PWD/key/application/TicketStore.cpp \
    $$PWD/key/application/TicketIngressService.cpp \
    $$PWD/key/protocol/InitPayloadEncoder.cpp \
    $$PWD/key/protocol/RfidPayloadEncoder.cpp \
    $$PWD/key/protocol/KeyDataFrameBuilder.cpp \
    $$PWD/key/protocol/TicketPayloadEncoder.cpp \
    $$PWD/key/protocol/TicketFrameBuilder.cpp \
    $$PWD/key/protocol/KeySerialClient.cpp \
    $$PWD/system/ui/systempage.cpp \
    $$PWD/system/application/SystemController.cpp \
    $$PWD/log/ui/logpage.cpp \
    $$PWD/log/application/LogController.cpp

HEADERS += \
    $$PWD/auth/ui/AccountSelectDialog.h \
    $$PWD/auth/ui/loginpage.h \
    $$PWD/auth/application/LoginController.h \
    $$PWD/auth/application/AuthFlowCoordinator.h \
    $$PWD/auth/domain/AuthTypes.h \
    $$PWD/auth/domain/ports/IAuthGateway.h \
    $$PWD/auth/domain/ports/ICredentialSource.h \
    $$PWD/auth/infra/password/authservice.h \
    $$PWD/auth/infra/password/AuthServiceAdapter.h \
    $$PWD/auth/infra/http/AuthGatewayAdapter.h \
    $$PWD/auth/infra/device/MockCredentialSource.h \
    $$PWD/auth/infra/device/CardSerialSource.h \
    $$PWD/auth/infra/device/FingerprintSource.h \
    $$PWD/workbench/ui/workbenchpage.h \
    $$PWD/workbench/application/WorkbenchController.h \
    $$PWD/keyboard/application/KeyboardController.h \
    $$PWD/keyboard/application/KeyboardModeResolver.h \
    $$PWD/keyboard/application/KeyboardPinyinEngine.h \
    $$PWD/keyboard/application/KeyboardPagePolicy.h \
    $$PWD/keyboard/application/KeyboardSizingPolicy.h \
    $$PWD/keyboard/application/KeyboardTargetAdapter.h \
    $$PWD/keyboard/application/pinyindecoderservice_p.h \
    $$PWD/keyboard/domain/KeyboardTypes.h \
    $$PWD/keyboard/ui/KeyboardContainer.h \
    $$PWD/keyboard/ui/CandidateBarWidget.h \
    $$PWD/keyboard/ui/NormalKeyboard.h \
    $$PWD/keyboard/ui/NumKeyboard.h \
    $$PWD/keyboard/ui/SymbolKeyboard.h \
    $$PWD/keyboard/ui/UrlKeyboard.h \
    $$PWD/key/ui/keymanagepage.h \
    $$PWD/key/application/KeySessionService.h \
    $$PWD/key/application/KeyManageController.h \
    $$PWD/key/application/SerialLogManager.h \
    $$PWD/key/application/KeyProvisioningService.h \
    $$PWD/key/application/TicketReturnHttpClient.h \
    $$PWD/key/application/TicketStore.h \
    $$PWD/key/application/TicketIngressService.h \
    $$PWD/key/protocol/InitPayloadEncoder.h \
    $$PWD/key/protocol/RfidPayloadEncoder.h \
    $$PWD/key/protocol/KeyDataFrameBuilder.h \
    $$PWD/key/protocol/TicketPayloadEncoder.h \
    $$PWD/key/protocol/TicketFrameBuilder.h \
    $$PWD/key/protocol/KeySerialClient.h \
    $$PWD/key/protocol/KeyProtocolDefs.h \
    $$PWD/key/protocol/LogItem.h \
    $$PWD/key/protocol/KeyCrc16.h \
    $$PWD/system/ui/systempage.h \
    $$PWD/system/application/SystemController.h \
    $$PWD/log/ui/logpage.h \
    $$PWD/log/application/LogController.h
